CREATE LOGIN HOTEL_ADMINISTRATOR
	WITH PASSWORD = '1111',
	DEFAULT_DATABASE = [BookingApartment],
	DEFAULT_LANGUAGE = [русский];

CREATE USER HOTEL_ADMINISTRATOR
	FOR LOGIN HOTEL_ADMINISTRATOR
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE TO HOTEL_ADMINISTRATOR;

--******
CREATE LOGIN CUSTOMER
	WITH PASSWORD = '2222',
	DEFAULT_DATABASE = [BookingApartment],
	DEFAULT_LANGUAGE = [русский];

CREATE USER CUSTOMER
	FOR LOGIN CUSTOMER
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE TO CUSTOMER;

SELECT * FROM USERS