CREATE LOGIN HOTEL_ADMINISTRATOR_LOG
	WITH PASSWORD = '1111',
	DEFAULT_DATABASE = [BookingApartment],
	DEFAULT_LANGUAGE = [русский];

CREATE USER HOTEL_ADMINISTRATOR
	FOR LOGIN HOTEL_ADMINISTRATOR_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE TO HOTEL_ADMINISTRATOR;

GRANT EXECUTE ON OBJECT:: xp_cmdshell to HOTEL_ADMINISTRATOR


--*******************************************************************
--*******************************************************************
--*******************************************************************
CREATE LOGIN CUSTOMER_LOG
	WITH PASSWORD = '2222',
	DEFAULT_DATABASE = [BookingApartment],
	DEFAULT_LANGUAGE = [русский];

CREATE USER CUSTOMER
	FOR LOGIN CUSTOMER_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE ON OBJECT:: GetSumForOrder TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: BookApartments TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: GetAllApartments TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: GetCities TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: GetHotelsForChosedCity TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: GetApartmentsByHotelStars TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: GetUniqPlacesByCityAndStars TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: GetApartmentsByHotelStarsAndPlaces TO CUSTOMER;
GRANT EXECUTE ON OBJECT:: GetApartmentsByHotelStarsAndPlacesAndCost TO CUSTOMER;



DROP USER HOTEL_ADMINISTRATOR;
DROP LOGIN HOTEL_ADMINISTRATOR_LOG;
DROP USER CUSTOMER;
DROP LOGIN CUSTOMER_LOG;

SELECT * FROM USERS