CREATE LOGIN HOTEL_ADMINISTRATOR_LOG
	WITH PASSWORD = '1111',
	DEFAULT_DATABASE = [BookingApartment],
	DEFAULT_LANGUAGE = [русский];

CREATE USER HOTEL_ADMINISTRATOR
	FOR LOGIN HOTEL_ADMINISTRATOR_LOG
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE TO HOTEL_ADMINISTRATOR;
GRANT INSERT TO HOTEL_ADMINISTRATOR;
GRANT ADMINISTER BULK OPERATIONS TO HOTEL_ADMINISTRATOR_LOG;


--*******************************************************************
--*******************************************************************
--*******************************************************************
CREATE LOGIN CUSTOMER
	WITH PASSWORD = '2222',
	DEFAULT_DATABASE = [BookingApartment],
	DEFAULT_LANGUAGE = [русский];

CREATE USER CUSTOMER
	FOR LOGIN CUSTOMER
	WITH DEFAULT_SCHEMA = [dbo];

GRANT EXECUTE TO CUSTOMER;


DROP USER HOTEL_ADMINISTRATOR;
DROP LOGIN HOTEL_ADMINISTRATOR;

SELECT * FROM USERS